# Caldera Original

units:
  pad: (u / 2) + 2
  

points:
  zones:
    matrix:
      columns:
        outer.key.column_net: P020 
        pinky.key.column_net: P022 
        ring.key.column_net: P024
        middle.key.column_net: P100 
        index.key.column_net: P011
        inner.key.column_net: P017
      rows:
        mod.row_net: P113
        bot.row_net: P115
        hom.row_net: P002
        top.row_net: P029
      anchor:
        # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
        shift: [100, -150]
  
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  board_left:
    - what: polygon
      operation: stack
      
      points:
        # Top left
        - ref: matrix_outer_top
          shift: [-pad, pad]
        # Top right
        - ref: matrix_inner_top
          shift: [pad, pad]
        # Bottom right
        - ref: matrix_inner_mod
          shift: [pad, -pad]
        # Bottom right
        - ref: matrix_outer_mod
          shift: [-pad, -pad]
  board_left_with_cutouts:
    - name: board_left
    - operation: subtract
      name: keys


pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      # Key switches
      keyswitches:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      # Diodes
      diode_main:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -9]
          rotate: 0

      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [50, -20]
          rotate: -90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_top
          shift: [40, 0]
          rotate: 0
        params:
            side: B
            pos: pos
            neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: matrix_inner_top
          shift: [20, 0]
          rotate: 0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: matrix_inner_top
            shift: [30, 0]
            rotate: 0
        params:
            side: B
            from: pos
            to: RAW