units:
  pad: u/2 + 3
points:
  zones:
    matrix:
      columns:
        outer:
          key:
            column_net: P020
        pinky:
          key:
            column_net: P022
        ring:
          key:
            column_net: P024
        middle:
          key:
            column_net: P100
        index:
          key:
            column_net: P011
        inner:
          key:
            column_net: P017
      rows:
        bottom:
        home:
        top:
      anchor:
        shift: [100, -100]
    thumbfan:
      anchor:
        ref: matrix_ring_bottom
        shift: [0.334u, -1u]
      columns:
        one:
        two:
        three:
          key:
            height: 1.5u
            origin: [-0.5u, -0.5u]
            shift: [0, -1.5]
            splay: -33
            
        four:
          key:
            spread: 1u
            stagger: -0.1u
            shift: [0, -.25u] 
        five:
          key:
            spread: 0
            stagger: 1u
            shift: [0, -.25u]
      rows:
        thumb:
          row_net: thumb_row
      

  mirror:
    ref: matrix_inner_top
    distance: 120
            
outlines:
  left_switch_cutouts:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  left_keycaps:
    - what: rectangle
      where: true
      size: [18, 18]
  board_left:
    - what: polygon
      operation: stack
      fillet: 1.5
      points:
        # Top
        - ref: matrix_outer_top
          shift: [-pad, pad]
        - ref: matrix_inner_top
          shift: [40, pad]
        - ref: thumbfan_five_thumb
          shift: [pad, 29.12]
        - ref: thumbfan_four_thumb
          shift: [pad, -pad]
        - ref: matrix_outer_bottom
          shift: [-pad, -pad]

  board_left_with_cutouts:
    - name: board_left
    - operation: subtract
      name: left_switch_cutouts
  
  board_left_with_keycaps:
    - name: board_left
    - operation: subtract
      name: left_keycaps
  

pcbs:
  left:
    outlines:
      main:
        outline: board_left

    footprints:
      keyswitches:
        where: true
        what: mx
        params:
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [22.5, -5.375]
          rotate: -90
      